language: php

php:
  - 'hhvm'
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'

matrix:
  allow_failures:
    # - php: hhvm

sudo: false

cache:
  # - apt

install:
  - composer update

script:
  - vendor/bin/phpunit
